davidd: create api/src/models/Orders.js
OwenConW/Final_Proyect pull request #36
Opened 2022-08-16 19:54 UTC by davidguti00

cree la tabla Orders en base de datos

2022-08-16 20:07 UTC, valentino-machuca requested changes
Change Cliente for Client

2022-08-16 20:21 UTC, davidguti00 reviewed
ya solucione, reemplace el nombre cliente por client

2022-08-17 03:22 UTC, davidguti00 reviewed
Ya hice todos los cambios en los modelos!!

2022-08-17 12:32 UTC, OwenConW approved these changes
kpooo

2022-08-17 12:40 UTC, valentino-machuca approved these changes

2022-08-17 14:40 UTC, merged