Jere client/src/components/catalog
OwenConW/Final_Proyect pull request #70
Opened 2022-08-19 19:11 UTC by atrconjerex

* Cree el componente Paginate.jsx
* Le agregué sus estilos
* Agregué al Catálogo el componente
* Modifiqué varias lineas del Catálogo, el componente Paginate ES DE PRUEBA, no se si es funcional, hasta que muestre las cards que antes mostraba.

2022-08-19 19:33 UTC, valentino-machuca requested changes
test paginate

2022-08-22 00:34 UTC, valentino-machuca submitted a review, later dismissed

2022-08-22 00:34 UTC, MartinMorales1504 submitted a review, later dismissed

2022-08-22 00:41 UTC, MartinMorales1504 approved these changes

2022-08-22 00:41 UTC, valentino-machuca approved these changes

2022-08-22 00:41 UTC, merged