Se modifico tipo de dato del modelo User, se creo la ruta para los review .get .post y .update
OwenConW/Final_Proyect pull request #97
Opened 2022-08-23 21:29 UTC by davidguti00

También actualice las relaciones,  las review de cada profesional vienen por id.

2022-08-23 22:05 UTC, OwenConW approved these changes

2022-08-23 23:11 UTC, atrconjerex requested changes
Pequeño cambio en este fichero:
api/src/routes/users/users.route.js

2022-08-23 23:11 UTC, atrconjerex commented on api/src/routes/users/users.route.js
> +    const { name, last_Name, date_of_Bird, mail, dni, image, phone, country, city, coordinate, description, isProfessional, profession } = req.body;
Modificar este pequeña correccion!! en la BD se llama: date_of_Birth

2022-08-23 23:11 UTC, atrconjerex commented on api/src/routes/users/users.route.js
> +                    date_of_Bird,
y acá también::: date_of_Birth

2022-08-24 01:01 UTC, davidguti00 commented on api/src/routes/users/users.route.js
> +    const { name, last_Name, date_of_Bird, mail, dni, image, phone, country, city, coordinate, description, isProfessional, profession } = req.body;
Ese campo esta en el modelo, no es obligatorio,

2022-08-24 01:02 UTC, davidguti00 commented on api/src/routes/users/users.route.js
> +                    date_of_Bird,
Es el mismo, para validar a futuro sobre si el usuario es mayor de edad

2022-08-24 02:03 UTC, davidguti00 commented on api/src/routes/users/users.route.js
> +                    date_of_Bird,
ya lo modifique, en el proximo commit!

2022-08-24 12:49 UTC, OwenConW submitted a review, later dismissed

2022-08-24 14:08 UTC, OwenConW approved these changes

2022-08-24 14:09 UTC, atrconjerex approved these changes
Excelentee amigoo!! Sos máquina

2022-08-24 14:10 UTC, atrconjerex approved these changes

2022-08-24 14:11 UTC, merged